### ISSUE TITLE
Bulk API to provide and consume services

### ISSUE THREAD

**Issue by lefou** [domino-osgi/domino#1]
Domino has a very nice type-safe syntax to consume and provide services. But the way, the API is designed, it is only possible to work with types known beforehand (compile time).

In case, were one needs to use generic collections of dependencies (their types), the Domino API (1.0.0) cannot be used, as variables can not be used in type parameter position.

Please add some API to work with generic dependency collections. Also a API to register a generic set of services would be helpful.

Example for dependencies not known at compile time:

```
// val services = Seq(classOf[ServiceA], classOf[ServiceB])
whenServicesPresent(services) { depsMap: Map[Class[_], Any] =>
  val serviceA = depsMap(classOf[serviceA])
  val serviceB = depsMap(classOf[serviceB])
}
```

**Comment by helgoboss** [comment]
Thanks for the request. I agree this is definitely missing. I would like to combine that with the possibility to express service requirements as full-blown objects (which I wanted to integrate anyway):

``` scala
val serviceDefs = Seq(
  ServiceDef(objectClass = classOf[ServiceA]),
  ServiceDef(objectClass = classOf[ServiceB], filter = Some("(provider=foo)"))
)

whenServicesPresent(serviceDefs) {
  // ...
}
```

Where `ServiceDef` is something like this (plus some sugar to be able to use the type-safe way we already have):

``` scala
case class ServiceDef(objectClass: Class[_], filter: Option[String] = None)
```

Questions:
- Do you see any problem with combining that?
- Is there any specific reason you want a `Map` passed as parameter for `whenServicesPresent`? I see the possibility of key clashes here.

**Comment by lefou** [comment]
I like your suggestion. `Seq[Class[_]]` can be easily mapped to `Seq[ServiceDef]`.

To your question. I don't see a key clash here. Even if the classes collection contains multiple instances of the same class, the gathered service would be the same (the first one). So, even if there is technically the chance of a clash, in fact it is not. To communicate that fact to the API user a `Set` could be used, but I prefer the `Seq` as it is more generic. If you also plan a version to get all available instances, multi map semantics could be used (`Map[Class[_],Seq[Any]]`).

What do you plan as function parameter? A map with `ServiceDef` as keys might be a bit heavyweight, but a map with class key might be ambiguous this time. ;-)

It would be very helpful, to also have a `providesService(Class[_])` API. Of course, something like `ServiceDef` as parameter would be ok, too.

**Comment by helgoboss** [comment]
I see. It's actually two requests, right?
1. Make it possible to specify class objects instead of type parameters in all service consuming methods
2. Make it possible to work with collections of services in `whenServicesPresent`

Let's assume we have these two service definitions:

``` scala
val serviceDefOne: ServiceDef[Any] = ServiceDef(objectClass = someClassObject) // type unknown at compile time
val serviceDefTwo: ServiceDef[ServiceB] = ServiceDef[ServiceB](filter = "(provider=foo)")
```

### 1. Class objects instead of type parameters

We are not dealing with collections here. So I would handle it as before, that is just passing the discovered services as separate parameters.

``` scala
whenServicesPresent(serviceDefOne, serviceDefTwo) { (serviceOne: Any, serviceTwo: ServiceB) =>
  // ...
}
```

### 2. Collections of services

I wonder whether it's a good idea to use a `Map` here. But maybe just because I have not been confronted with such a use case yet. 

If we go the `Map` way, I would indeed use `ServiceDef` as key:

``` scala
val serviceDefs: Seq[ServiceDef[Any]] = Seq(serviceDefOne, serviceDefTwo)

whenServicesPresent(serviceDefs) { depsMap: Map[ServiceDef[Any], Any] =>
  // ...
}
```

If not, I would just pass a sequence (same order like `ServiceDef` sequence).

Can you illustrate your use case?

**Comment by lefou** [comment]
(Sorry for the longish post. At the end you will find a summary!)

I had some signature like this in mind:

``` scala
def whenServicesPresent(serviceDefs: ServideDef*)(f: Map[ServiceDef,Any] => Any)
```

But a `Seq[(ServiceDef,Any)]` might be good, too, as it can be converted to a map very easily. 

But in the end, the user might profit the most from a new type (Requirements, working title), as we could provide more runtime checks and logging, when e.g. a type is requested, that was not provided, e.g.:

``` scala
trait Requirements {
  def get[T](serviceType: Class[T]): T
  def get[T](serviceDef: ServiceDef[T]: T
  // more convenience functions as you like, e.g.
  // def toMap: Map[ServiceDef[Any], Any]
}

def whenServicesPresent(serviceDef: ServideDef*)(f: Requirements => Any)
```

I would argue, that in most cases when you have to deal with more than one generic class, all you have is a collection of class objects. The above signature supports both, collections and explicit parameters. So yes, its two request in one, but it can be solved with one solution.

Until now, I assumed, we are talking about an addition for the special case, where I don't know the class types at compile time. I would say, in those cases, it is ok to only support the "collection of services" case (which is the above outlined one). I think, the first case "class object instead of type parameters" has a limited use and is not needed at all. In most cases when you know how to unpack the result tuple you already know the types, so does the compiler, which is the already present API.

**I fear, I could not make my clear idea so clear with my poor English. Let me sumarize again:**

**Story 1:** As an API user, I want to depend on a collection of services by providing their class objects. Example:

``` scala
val someServiceClasses: Seq[Class[_]] = // get from somewhere else

whenServicesPresent(someServiceClasses.map(c => ServiceDef(objectClass = c)) { reqs: Requirements =>
  val someServices = someServiceClasses.map { c => reqs.get(c) )
  // do something with them
}
```

**Story 2:** As an API user, I want to register a service with the given class objects as names. Example:

``` scala
val container = // Some magic dependency container, think of as Spring Container or Generic Remoting Service

val servicesToPublish: Seq[Class[_]] = // got from a config object of file

servicesToPublish { s: Class[_] =>
  val instance = container.getBean(s)
  instance.providesService(s)
}
```

Here are some real use cases:
- Register services created by a bundle-private spring container into service registry
- Consume a list of services and publish them via a proprietary remoting solution (server side)
- Receive remote services by a proprietary remoting solution and register them into service registry (client side)

**Comment by helgoboss** [comment]
Thanks for the detailled explanation! I have to digest that first :) Hope I get back to you tomorrow.

**Comment by helgoboss** [comment]
These are some interesting new use cases.

I think there's not much to discuss about story 2. I will just provide a `providesService` method which takes a `Class` object as shown in your example.

Story 1 is a different beast :) I'd like to find with you the "right" way to support this. Two of my guidelines for developing Domino are:
- Prefer Scala's powerful built-in types over own ones where it makes sense
- Prefer basic composable building blocks over syntactic sugar

Taking this into account, I come up with following suggestion:

``` scala
val serviceDefs: Seq[ServiceDef[Any]] = // ...

whenServicesPresent(serviceDefs) { mappings: Seq[Tuple2[ServiceDef[Any], Any]] =>
  // Can use Scala's built-in way to make a map
  val depsMap: Map[ServiceDef[Any], Any] = mappings.toMap

  // Supports your initial code example "Query by class object". We don't have to 
  // construct the ServiceDef object by hand because I will put an implicit conversion 
  // into ServiceDef's companion object (that should always apply, doesn't need to be 
  // imported explicitly). 
  val serviceA = depsMap(classOf[ServiceA])

  // Supports the multi-map semantics you wrote about with Scala's built-in way.
  val multiMap: Map[ServiceDef[Any], List[Any]] = mappings groupBy { _._1 }

  // Supports easy iteration
  mappings foreach { case (serviceDef, service) =>
    // ...
  }
}
```

So I suggest a sequence of tuples (`Tuple2`) because:
1. A tuple nicely shows that we are dealing with a _mapping_ here - a mapping from a service criteria to an actual discovered service.
2. A tuple is a kind of first-class citizen in Scala. It automatically supports all of the scenarios you mentioned by using idiomatic Scala code. This might lead to a faster learning curve and feel more familar.

However, one advantage I see in introducing a new type `Requirements` is that it's open for future additions without breaking the API. So I'm not quite sure yet. What do you think? Do you see more advantages?

In any case, if I would add a new type, I would also add a method which returns a sequence of tuples.

**Comment by helgoboss** [comment]
Oh, just realized:
1. Multi-map semantics don't make sense the way I used them. The list size will never be greater than one. Then we could just as well take a `Map`.
2. `depsMap(classOf[ServiceA])` would find only those services for which no filter was given in `ServiceDef`. To really find every service for a given class object, we would need something like this:
   
   ``` scala
   mappings filter { _._1.objectClass == classOf[ServiceA] }
   ```
   
   or
   
   ``` scala
     val multiMap = mappings map { t => (t._1.objectClass, t._2) } groupBy { _._1 }
     multiMap.get(classOf[ServiceA])
   ```
   
   Both pretty complicated. Makes me tend more towards your `Requirements` suggestion again.

**Comment by lefou** [comment]
> Taking this into account, I come up with following suggestion:
> 
> ``` scala
> val serviceDefs: Seq[ServiceDef[Any]] = // ...
> 
> whenServicesPresent(serviceDefs) { mappings: Seq[Tuple2[ServiceDef[Any], Any]] =>
>   // Can use Scala's built-in way to make a map
>   val depsMap: Map[ServiceDef[Any], Any] = mappings.toMap
> 
>   // Supports your initial code example "Query by class object". We don't have to 
>   // construct the ServiceDef object by hand because I will put an implicit conversion 
>   // into ServiceDef's companion object (that should always apply, doesn't need to be 
>   // imported explicitly). 
>   val serviceA = depsMap(classOf[ServiceA])
> 
>   // Supports the multi-map semantics you wrote about with Scala's built-in way.
>   val multiMap: Map[ServiceDef[Any], List[Any]] = mappings groupBy { _._1 }
> 
>   // Supports easy iteration
>   mappings foreach { case (serviceDef, service) =>
>     // ...
>   }
> }
> ```
> 
> So I suggest a sequence of tuples (Tuple2) because:
> 1. A tuple nicely shows that we are dealing with a mapping here - a mapping from a service criteria to an actual discovered service.
> 2. A tuple is a kind of first-class citizen in Scala. It automatically supports all of the scenarios you mentioned by using idiomatic Scala code. This might lead to a faster learning curve and feel more familar.

I agree completely with you and would consider this the best solution.

The use cases that favour the `Requirements` type are pretty much advanced in my eyes. But it's all about convenience and not about possibilities. Everything is already possible with `Seq[(ServiceDef -> Any)]`, so I suggest to leave a new type out for now.

I would love to see those discussed additions in Domino. Thank you very much for your work and time!

Regards,
Tobias

**Comment by lefou** [comment]
Although, I created this feature request by myself, I think it should not be implemented in Domino directly. As Domino is easily extensible through the generic capsule concept, this feature can be first developed as separate bundle/project. The use case is to uncommon for a DSL.
