### ISSUE TITLE
Create a Maven project redirect for `org.helgoboss:domino`

### ISSUE THREAD

**Issue by lefou** [domino-osgi/domino#10]
It should redirect to `com.github.domino-osgi:domino_2.10`.

I don't know, if we can create a redirect and keep to 1.0.0 at the same time, but it would be cool.

@helgoboss How do you think about it?

**Comment by helgoboss** [comment]
I think the package structure has changed. So a redirect from `org.helgoboss:domino:1.0.0` to `com.github.domino-osgi:domino_2.10:1.1.0` would be problematic. Therefore I wouldn't bother with redirects.

Or did you have something else in mind?

**Comment by lefou** [comment]
This is a good argument. But that means current users will never recognize the availability of updates except if they visit the project page. Sounds fair enough, given that you believe the user count isn't that high. Do you have any usage numbers, e.g. based on OSSRH? Could you please add a note about the move on the old project page?

**Comment by helgoboss** [comment]
@lefou I added a [prominent note](http://www.helgoboss.org/projects/domino/) about the move. My guess is, people will immediately jump over to GitHub just to get released from the disturbing red "alert" color. Mission accomplished ;)

If I interpret the stats on OSSRH correctly, the user count is really not high. Anyway, I guess whoever has issues with Domino 1.0.0 or is interested in future versions will not just rely on Maven versions plugin but visit the project page.

**Comment by lefou** [comment]
@helgoboss Great! Also thank you for the review and completion of the README.
