### ISSUE TITLE
Remove Logging trait from DominoActivator

### ISSUE THREAD

**Issue by lefou** [domino-osgi/domino#11]
The `Logging` trait introduces a public `log` method and lots of protected `val`s. It's inherited by `DominoActivator` but never used anywhere. I've seen many situation, where SLF4J was the preferred logging solution but the inherited `log` variable name collided with the own logger. Also, the provided logger in not lazily acquired (despite the fact, `fallbackLogger` is declared lazy) and depends on an early avaliable OSGi `LogService`.

We loose nothing, if we remove it from `DominoActivator`. A potential user can still simply mix the trait into the concrete activator class.

What do you think?

**Comment by frgomes** [comment]
Agree. The user can simply mixin if needed.
