### ISSUE TITLE
Are there any rules for Capsule ordering of start ?

### ISSUE THREAD

**Issue by PhilAndrew** [domino-osgi/domino#20]
I have a:

`class OsgiCapsule extends Capsule {`

which is added in a DominoActivator

```
  whenBundleActive {

    val m = new OsgiCapsule()
    addCapsule(m)
```

I found the start on OsgiCapsule gets called immediately when I added it on addCapsule, Is that the rule?

**Comment by lefou** [comment]
Yes, that is the rule for the current implementation (`DynamicCapsuleContext`).
